### ISSUE TITLE
清洗好的数据集会开源吗？

### ISSUE THREAD

**Issue by echo-valor** [charent/ChatLM-mini-Chinese#12]
楼主好，想使用清洗好的数据集自己做一个增量预训练

**Comment by charent** [comment]
因为原始数据集二次加工后再开源的话，可能涉及版权问题，所以暂时没有开源清洗好的数据的计划。但是清洗方法是开源的，你可以自己根据`readme.md`中的地址去下载原始数据集，按照[raw_data_process.py](https://github.com/charent/ChatLM-mini-Chinese/blob/main/utils/raw_data_process.py)提供的方法清洗就可以了。
