### ISSUE TITLE
Hello, 第一次使用，请问运行时出现 unsupported operand type(s) for |: 'types.GenericAlias' and 'type' 是什么问题？

### ISSUE THREAD

**Issue by yugu91** [charent/ChatLM-mini-Chinese#15]
官方的demo都已经运行使用了，使用git仓库运行api、训练和微调都遇到了这个错误，具体位置是：

Traceback (most recent call last):
  File "/Users/xxxx/xxx/ChatLM-mini-Chinese/sft_train.py", line 16, in <module>
    from utils.functions import get_T5_config
  File "/Users/xxxx/xxx/ChatLM-mini-Chinese/utils/functions.py", line 27, in <module>
    def _get_doc_mini_hash(doc: list[str] | str, num_perm: int) -> MinHash:
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'type'

**Comment by charent** [comment]
你的python版本是多少？我这边python3.10、3.11都没有问题。
你试试把27行改成下面这行试试，
```python
def _get_doc_mini_hash(doc, num_perm):
```
应该是你的环境不支持`list[str] | str`这种写法，如果还有其他行报类似的错，就把`参数:`的冒号及后面的参数类型删掉。

**Comment by yugu91** [comment]
我这边是3.9，我升级一下试试
