### ISSUE TITLE
為甚麼我啟動API會出現這個

### ISSUE THREAD

**Issue by Adolph3671** [charent/ChatLM-mini-Chinese#16]
启动的进程个数:1
INFO:     Will watch for changes in these directories: ['C:\\ChatLM-mini-Chinese']
INFO:     Uvicorn running on http://127.0.0.1:8812 (Press CTRL+C to quit)
INFO:     Started reloader process [5640] using StatReload
INFO:     Started server process [4988]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:52111 - "GET / HTTP/1.1" 404 Not Found

**Comment by charent** [comment]
应该是你的请求头没写对，或者请求的地址没写对，要加上`--header 'Authorization: Bearer you_api_key' `。参考
```
curl --location '127.0.0.1:8812/api/chat' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer Bearer' \
--data '{
    "input_txt": "感冒了要怎么办"
}'
```
