### ISSUE TITLE
请教一个问题，生成的回复重复

### ISSUE THREAD

**Issue by shinerdeng** [charent/ChatLM-mini-Chinese#17]
请教一个问题，用readme提到的数据集做预训练，和readme一样下降到3.几就立即停止训练了。还没有sft和RLHF。直接用cli_demo，stream=False测试，输出如下回复，请问这是预训练时间不够还是因为没有sft呢？

用户：你好
你好
ChatBot：
你好，你好，你好，你的情况，考虑为肾虚，可以服用六味地黄丸或六味地黄丸进行治疗，同时服用六味地黄丸进行治疗，不吃辛辣刺激性的食物很重要。

**Comment by charent** [comment]
应该是没有进行sft导致的，你的提问中没有提及病情，回答像是吐出训练数据了。顺便问一句，从0开始预训练的吗？还是说从这个项目提供的rlhf后的模型开始的？训练的数据量有多大？小模型、小数据集一般要3-4个epoch就可以了

**Comment by charent** [comment]
忘了补充了😂，你可以试试把`generate`函数的参数`repetition_penalty`设置为`1.2`试试，这个值越大，越不容易产生重复值。这是对重复词惩罚的参数。代码在[chat_model.py#L43](https://github.com/charent/ChatLM-mini-Chinese/blob/14bbd7437417fc049d91669fb98177092ab37bbe/model/chat_model.py#L43)，现在的版本被我注释掉了。
