### ISSUE TITLE
Why do I get stuck loading the dataset after running it

### ISSUE THREAD

**Issue by anyiz** [charent/ChatLM-mini-Chinese#24]
The system I am running is Windows
![bug](https://github.com/charent/ChatLM-mini-Chinese/assets/95127377/e2da76bc-0bb5-4eda-8480-9f2ea926ece5)

**Comment by charent** [comment]
What's your training arguments? e.g. `batch_size` , `max_seq_len`  and  `gradient_accumulation_steps`.  

Using the default training arguments approximately use 22GB-23GB GPU Memory for training model, DO NOT include datasets and python scripts' usage. 

As your are using `CPU` for training and available RAM is `22.47 GB`,  it may lead to system memory swap and training with cpu is toooooo slow, it looks like stucking of your system.

**Comment by charent** [comment]
I forgot that, 22GB-23GB GPU Memory usge is base on amp-bfloat16，cpu can NOT compute hafl float data type, fp32 instead，it may use more then 23GB RAM.

**Comment by anyiz** [comment]
> I forgot that, 22GB-23GB GPU Memory usge is base on amp-bfloat16，cpu can NOT compute hafl float data type, fp32 instead，it may use more then 23GB RAM.

I have solved this problem. Thank you for your reply, but I have encountered a new problem: during my training process, I always encountered TypeError when reading data: 'NoneType' object is not subscribable. This error caused the program to exit abnormally. I have roughly checked my data and there is no empty data
![bug](https://github.com/charent/ChatLM-mini-Chinese/assets/95127377/5dc00253-4971-4cea-b472-2c0cce185ca6)

**Comment by charent** [comment]
The error throwed by this file, line 102, as below picture showed.
![image](https://github.com/charent/ChatLM-mini-Chinese/assets/19562666/cd27e5c2-2282-4241-a439-e4bf570d52bc)
It looks like data field `prompt` or `response`  being none type, `prompt` or `response` 's data type must be string and length > 0.  
 Check your dataset file if any NONE TYPE object (for example, loading your dataset with `pandas`, use `pd.dropna()` to drop `None` data), be sure your dataset is clean.

**Comment by anyiz** [comment]
> The error throwed by this file, line 102, as below picture showed. ![image](https://private-user-images.githubusercontent.com/19562666/301701767-cd27e5c2-2282-4241-a439-e4bf570d52bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NDU4NzYsIm5iZiI6MTcwNjg0NTU3NiwicGF0aCI6Ii8xOTU2MjY2Ni8zMDE3MDE3NjctY2QyN2U1YzItMjI4Mi00MjQxLWE0MzktZTRiZjU3MGQ1MmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDAzNDYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlMDAyZDk1ZTllODM0ZTVhOTEwMWRmYjI0NTFmOTFjYzNkNDY1ZDUwOTFkOWQ3ZjA5ZGNlMTcwN2MwY2EyNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xzijE0qgsVQINcCxwfwHoIYKufq3albIl6TRmzk0yjI) It looks like data field `prompt` or `response` being none type, `prompt` or `response` 's data type must be string and length > 0. Check your dataset file if any NONE TYPE object (for example, loading your dataset with `pandas`, use `pd.dropna()` to drop `None` data), be sure your dataset is clean.

Indeed, there was an issue with my data. When I was training with multiple GPUs, there was an issue with NCCL
![bug](https://github.com/charent/ChatLM-mini-Chinese/assets/95127377/237ce086-f83b-457a-989d-695e448fd843)
![peizhi](https://github.com/charent/ChatLM-mini-Chinese/assets/95127377/656e58ea-868f-4b53-af98-1981517cbb24)

**Comment by charent** [comment]
How many gpus do you hava? What's your linux kernel version? For running with `torch >= 2.1` and `accelerate` , linux kernel version should be >= 5.5.    

This code is running well on my machine with 2 gpus. It looks like your environment problem.   

You should google it or see this [accelerate/issues/2174#issuecomment-1821295563](https://github.com/huggingface/accelerate/issues/2174#issuecomment-1821295563).

**Comment by anyiz** [comment]
> How many gpus do you hava? What's your linux kernel version? For running with `torch >= 2.1` and `accelerate` , linux kernel version should be >= 5.5.
> 
> This code is running well on my machine with 2 gpus. It looks like your environment problem.
> 
> You should google it or see this [accelerate/issues/2174#issuecomment-1821295563](https://github.com/huggingface/accelerate/issues/2174#issuecomment-1821295563).

I trained on four A10 graphics cards, and the Linux kernel version is 5.15.0-91-generic. Is there any other way to solve this besides upgrading my kernel version? Upgrading the version involves too much, and besides that, I tried to configure the environment variable NCCL_ P2P_ DISABLE=1 and NCCL_ IB_ DisaBLE=1, used to disable P2P but still does not work
![bug](https://github.com/charent/ChatLM-mini-Chinese/assets/95127377/3bbb9e9f-7577-4552-af71-98083445e974)

**Comment by charent** [comment]
Kernel  5.15 is ok. Does it works with one gpu?  Have you run `accelerate config` command to configure your machine? have you try this code? `--num_processes` means how many gpu you want to use.
```python
# this project trainer
accelerate launch --multi_gpu --num_processes 4 ./train.py train

# huggingface trainer
accelerate launch --multi_gpu --num_processes 4 pre_train.py
```
If `Some NCCL operations have failed or timed out` error only happen in evaluate stage, check if there is any available gpu memory at that time (mabe some of your evaluate data sequence is too long, lead to cuda OOM), or try to skip the evaluate stage, do traing only.

**Comment by anyiz** [comment]
> Kernel 5.15 is ok. Does it works with one gpu? Have you run `accelerate config` command to configure your machine? have you try this code? `--num_processes` means how many gpu you want to use.
> 
> ```python
> # this project trainer
> accelerate launch --multi_gpu --num_processes 4 ./train.py train
> 
> # huggingface trainer
> accelerate launch --multi_gpu --num_processes 4 pre_train.py
> ```
> 
> If `Some NCCL operations have failed or timed out` error only happen in evaluate stage, check if there is any available gpu memory at that time (mabe some of your evaluate data sequence is too long, lead to cuda OOM), or try to skip the evaluate stage, do traing only.

Yes, I ran the program using the instructions above, and the program did indeed run out of GPUs during the evaluation phase. Setting the number of GPUs to 2 using the same instructions also caused the same problem. I am puzzled why I set the batch to be very small and the GPUs to be OOM. How can I modify the code to skip the evaluation phase and only focus on training
![bug2](https://github.com/charent/ChatLM-mini-Chinese/assets/95127377/c3f6dbf1-b5ec-4454-805d-e135b2a9ab4f)

![bug1](https://github.com/charent/ChatLM-mini-Chinese/assets/95127377/b3f50fca-49a0-42b4-8934-216850cefdbd)

**Comment by charent** [comment]
1. Some of your evaluate data sequence is too long, it will pad to max length in a batch while runing evaluate, may lead to cuda OOM.
2. How to skip the evaluation stage?
- if you are using this project trainer, comment or delete [model/trainer.py#Line373](https://github.com/charent/ChatLM-mini-Chinese/blob/be5798fc03cd3662b5419e67dc920dd2e3e67135/model/trainer.py#L373) to [model/trainer.py#Line400](https://github.com/charent/ChatLM-mini-Chinese/blob/be5798fc03cd3662b5419e67dc920dd2e3e67135/model/trainer.py#L400), model checkpoint will save in `model/trainer.py#L344`
- if your are using huggingface trainer
set  `eval_dataset=None`， in [pre_train.py#Line108](https://github.com/charent/ChatLM-mini-Chinese/blob/be5798fc03cd3662b5419e67dc920dd2e3e67135/pre_train.py#L108)

**Comment by anyiz** [comment]
> 1. Some of your evaluate data sequence is too long, it will pad to max length in a batch while runing evaluate, may lead to cuda OOM.
> 2. How to skip the evaluation stage?
> 
> * if you are using this project trainer, comment or delete [model/trainer.py#Line373](https://github.com/charent/ChatLM-mini-Chinese/blob/be5798fc03cd3662b5419e67dc920dd2e3e67135/model/trainer.py#L373) to [model/trainer.py#Line400](https://github.com/charent/ChatLM-mini-Chinese/blob/be5798fc03cd3662b5419e67dc920dd2e3e67135/model/trainer.py#L400), model checkpoint will save in `model/trainer.py#L344`
> * if your are using huggingface trainer
>   set  `eval_dataset=None`， in [pre_train.py#Line108](https://github.com/charent/ChatLM-mini-Chinese/blob/be5798fc03cd3662b5419e67dc920dd2e3e67135/pre_train.py#L108)

It is indeed this problem. I will comment out the evaluation code and he can train normally. Thank you for your answer
