### ISSUE TITLE
请教“3.3 Tokenizer训练”如何运行？

### ISSUE THREAD

**Issue by ybdesire** [charent/ChatLM-mini-Chinese#25]
按照“3.2 从克隆仓库代码开始”步骤
完成了如下三个步骤：
3.2.1 克隆项目
3.2.2 安装依赖
3.2.3 下载预训练模型及模型配置文件

最终model_save目录文件结构如下：
```
(aaaenv) root@bcdeee:/ChatLMChinese02B/ChatLM-mini-Chinese# ll model_save/
total 734283
drwxr-xr-x 1 root root        12 Feb  4 10:53 ./
drwxr-xr-x 1 root root        25 Feb  4 10:49 ../
-rw-r--r-- 1 root root     24974 Feb  4 10:44 README.md
-rw-r--r-- 1 root root       803 Feb  4 10:44 config.json
-rw-r--r-- 1 root root       126 Feb  4 10:44 configuration.json
-rw-r--r-- 1 root root        95 Feb  4 10:44 configuration_chat_model.py
drwxr-xr-x 1 root root         8 Feb  4 10:44 description/
-rw-r--r-- 1 root root       142 Feb  4 10:44 generation_config.json
-rw-r--r-- 1 root root 750794624 Feb  4 10:44 model.safetensors
-rw-r--r-- 1 root root      3208 Feb  4 10:44 modeling_chat_model.py
-rw-r--r-- 1 root root         0 Feb  4 09:48 put_model_files_here
-rw-r--r-- 1 root root        75 Feb  4 10:44 special_tokens_map.json
-rw-r--r-- 1 root root   1077208 Feb  4 10:44 tokenizer.json
-rw-r--r-- 1 root root      1420 Feb  4 10:44 tokenizer_config.json
```

**请问：**
3.3 Tokenizer训练
这个步骤，是要这样运行吗？
```
(aaaenv) root@bcdeee:/ChatLMChinese02B/ChatLM-mini-Chinese# python utils/train_tokenizer.py
```

我`python utils/train_tokenizer.py`这样运行报错如下：
```
  File "/ChatLMChinese02B/ChatLM-mini-Chinese/utils/train_tokenizer.py", line 23, in <module>
    from config import PROJECT_ROOT
ModuleNotFoundError: No module named 'config'
```

是不是需要先从哪里下载语料？在运行3.3之前，需要先下载并处理语料吗？

**Comment by charent** [comment]
报错的问题你重新拉一下代码就可以了。训练tokenizer运行`python utils/train_tokenizer.py`就可以了，默认训练`char level`的tokenizer，如果需要训练`byte level`的tokenizer，更改``的`train_my_huggingface_wiki_tokenizer`函数的`token_type='byte'`即可

需要先获取语料，获取语料参考：[issues/2#issuecomment-1888905870](https://github.com/charent/Phi2-mini-Chinese/issues/2#issuecomment-1888905870)。
或者下载这个数据集[roots_zh-cn_wikipedia](https://huggingface.co/datasets/bigscience-data/roots_zh-cn_wikipedia)，自己写个脚本转换为纯文本的`wiki.simple.txt`文件，放到`data/raw_data`下就可以了，你也可以自己修改文件位置[train_tokenizer.py#L79](https://github.com/charent/ChatLM-mini-Chinese/blob/a2f84ebb1f833b00de93fb330f42e85fee72fd67/utils/train_tokenizer.py#L79)

**Comment by ybdesire** [comment]
@charent 非常感谢您的回复，我再试试
