### ISSUE TITLE
请问，如果有新的内容需要添加，是否需要全部重新训练？

### ISSUE THREAD

**Issue by kideve** [charent/ChatLM-mini-Chinese#29]
非常感谢您的奉献和分享！
我想请教的内容如题：是否在新的内容出现后需要对已有的数据也要全部重新训练一次，谢谢！
祝新春快乐

**Comment by charent** [comment]
看你自己的需求和具体数据吧，如果是大量的文章、新闻，条件允许可以再训练一次，反正模型不大。如果需要新的指令（比如三元组信息抽取）直接做sft微调就好了。至于直接用新数据基于dpo模型再跑一遍预训练，我没有做过实验。现在对新数据、本地私有数据接入语言模型的主流方法是检索增强生成（RAG）。

**Comment by kideve** [comment]
谢谢您的回复~
