### ISSUE TITLE
请问数据预处理里面bell_open_source/train_0.8M_CN.json是在哪里下载的呀

### ISSUE THREAD

**Issue by PshySimon** [charent/ChatLM-mini-Chinese#30]
如题，我在huggingface没找到这个文件

**Comment by charent** [comment]
我有点忘了，我翻了我本地的数据处理代码，没有发现加工得到`train_0.8M_CN.json`的代码😂。不太确定是不是原作者`bell_open_source`删除了这个数据集，问题不大，可以用其他的数据代替，反正都是sft的数据集。

**Comment by PshySimon** [comment]
还有就是finetune的数据集train_conv_2.json也没有找到😂，不知道是不是改名了的数据集

**Comment by charent** [comment]
还有找不到的话，那有可能是我本地筛选的代码删了或者没推送上来😂。sft数据是出自`BELLE`这里的，你从这里取就可以了：[10M中文数据集](https://github.com/LianjiaTech/BELLE/tree/main/data/10M)，10M肯定比我筛选后的多（我筛选主要是剔除翻译任务（英文少，表现不佳，可以通过加入英文语料重新训练tokenizer解决）、表格任务、多轮对话只取第一轮）。

**Comment by PshySimon** [comment]
我有个疑问，为什么我自己训练的tokenizer都是这种带有奇怪符号的，我看你上传到huggingface上的就没有这种，这是怎么得到的，有什么参数可以控制吗？

▁江南40932
▁接近40933
▁性别40934
中担任40935
单行本40936

**Comment by charent** [comment]
`▁`这是`Metaspace`，如果不加这个，encode、decode遇到空格可能会出问题。我上传的其实也有，只不过`▁`这个字符不在我的词表里面，encode出来会是`[unk]`，算是一个bug吧，但是模型已经训练完成了，修不了了😂。

控制代码如下，你可以在最新分支的`train_tokenizer.py`文件中找到。`Metaspace`类有两个参数，一个是`replacement`，默认就是`▁`。另一个参数是`add_prefix_space`，表示是否要在句子开头添加`▁`前缀，默认为`True`，以及是否将空格合并到后面的单词中，比如`say hello`中的` hello`(h前面有个空格)看成是一个单词，否则空格和'\n'，'\t'一样都会被看成一个字符。 
我做实验的时候，设置`add_prefix_space=False`时，编码、解码空格都有问题，你可以自己拿个包含中、英的小语料试一下。
```python
tokenizer.pre_tokenizer = tokenizers.pre_tokenizers.Sequence(
    [Punctuation(), Digits(individual_digits=True), Metaspace()]
)
tokenizer.decoder = decoders.Metaspace()
```

**Comment by PshySimon** [comment]
好吧，对了还有一个问题，我在做sft的时候，chat_small_t5.best.bin这个文件是huggingface上面的model.safetensor吗？我直接用这个报错，找不到key x。有没有只做了预训练没做sft之后的权重下载呀

**Comment by charent** [comment]
我做sft的时候使用的是预训练后的模型。直接用我发布的dpo后的模型做sft也是可以的，把`config.py`的`finetune_from_ckp_file`改为模型所在的文件夹就可以了（里面要包含多个文件，和reame.md中要求的`model_save`文件夹一致）。如果你要使用本项目的trainer，你要自己改一下`model/trainer.py`中模型加载的代码。huggingface trainer的`sft_train.py`加载模型代码如下，`load_state_dict`表示加载pyroch模型的bin文件。
```python
# step 2. 加载预训练模型
model = None
if os.path.isdir(config.finetune_from_ckp_file):
    # 传入文件夹则 from_pretrained
    model = TextToTextModel.from_pretrained(config.finetune_from_ckp_file)
else:
    # load_state_dict
    t5_config = get_T5_config(T5ModelConfig(), vocab_size=len(tokenizer), decoder_start_token_id=tokenizer.pad_token_id, eos_token_id=tokenizer.eos_token_id)
    model = TextToTextModel(t5_config)
    model.load_state_dict(torch.load(config.finetune_from_ckp_file, map_location='cpu')) # set cpu for no exception
```
