### ISSUE TITLE
RuntimeError: No executable batch size found, reached zero

### ISSUE THREAD

**Issue by suiyueyousan** [charent/ChatLM-mini-Chinese#40]
初学者自己笔记本跑代码，帮忙指教一下，4G独显。
![微信图片_20240331230744](https://github.com/charent/ChatLM-mini-Chinese/assets/27804521/b8528583-3893-4377-ad8b-63b380ff648c)

**Comment by charent** [comment]
你这个问题和这个是一样的，你可以参考下[issues/37](https://github.com/charent/ChatLM-mini-Chinese/issues/37)
> > 那可能是你的数据集有问题，检查一下是不是有空数据。
> 
> 嗯，找到原因了，好像是单条数据的token太长了，我做了个截断后就不会爆显存了，谢谢大佬。

**Comment by suiyueyousan** [comment]
谢谢确实是这个问题
