### ISSUE TITLE
如何加载sft后的模型？

### ISSUE THREAD

**Issue by mingshenhk** [charent/ChatLM-mini-Chinese#41]
我sft训练后发现model_save文件夹中多了一个sft文件夹，其中有checkpoints-10000还有一些其他的，如何加载并使用sft后的模型呢？

**Comment by charent** [comment]
在推理阶段使用的话，修改`config.py`文件的这里：[config.py#L15](https://github.com/charent/ChatLM-mini-Chinese/blob/1437915ce22ff9233ebd5d3a5d424469eea7936c/config.py#L15)。如果当作为dpo阶段的模型使用，修改`config.py`文件的这里：[config.py#L34](https://github.com/charent/ChatLM-mini-Chinese/blob/1437915ce22ff9233ebd5d3a5d424469eea7936c/config.py#L34)

`checkpoints-10000`是检查点模型文件，方便你训练出现异常时回退到检查点，或者后面训练过拟合了就直接使用检查点的模型。直接保存到sft目录下的模型文件是训练完成后保存的。
