### ISSUE TITLE
预训练数据集必须是{“prompt”: "response":}的格式么？

### ISSUE THREAD

**Issue by dbcSep03** [charent/ChatLM-mini-Chinese#46]
{
    "prompt": "对于花园街，你有什么了解或看法吗？",
    "response": "花园街（是香港油尖旺区的一条富有特色的街道，位于九龙旺角东部，北至界限街，南至登打士街，与通菜街及洗衣街等街道平行。现时这条街道是香港著名的购物区之一。位于亚皆老街以南的一段花园街，也就是\"波鞋街\"整条街约150米长，有50多间售卖运动鞋和运动用品的店舖。旺角道至太子道西一段则为排档区，售卖成衣、蔬菜和水果等。花园街一共分成三段。明清时代，花园街是芒角村栽种花卉的地方。此外，根据历史专家郑宝鸿的考证：花园街曾是1910年代东方殷琴拿烟厂的花园。纵火案。自2005年起，花园街一带最少发生5宗纵火案，当中4宗涉及排档起火。2010年。2010年12月6日，花园街222号一个卖鞋的排档于凌晨5时许首先起火，浓烟涌往旁边住宅大厦，消防接报4"
}
为什么预训练数据集是如上格式，不应该是拼接文本么？

**Comment by IcyFeather233** [comment]
数据集换成这样是因为原始数据集就是问答对，方便处理，最后是做了拼接的，见：https://github.com/charent/ChatLM-mini-Chinese/blob/1437915ce22ff9233ebd5d3a5d424469eea7936c/utils/raw_data_process.py#L975

**Comment by charent** [comment]
> { "prompt": "对于花园街，你有什么了解或看法吗？", "response": "花园街（是香港油尖旺区的一条富有特色的街道，位于九龙旺角东部，北至界限街，南至登打士街，与通菜街及洗衣街等街道平行。现时这条街道是香港著名的购物区之一。位于亚皆老街以南的一段花园街，也就是"波鞋街"整条街约150米长，有50多间售卖运动鞋和运动用品的店舖。旺角道至太子道西一段则为排档区，售卖成衣、蔬菜和水果等。花园街一共分成三段。明清时代，花园街是芒角村栽种花卉的地方。此外，根据历史专家郑宝鸿的考证：花园街曾是1910年代东方殷琴拿烟厂的花园。纵火案。自2005年起，花园街一带最少发生5宗纵火案，当中4宗涉及排档起火。2010年。2010年12月6日，花园街222号一个卖鞋的排档于凌晨5时许首先起火，浓烟涌往旁边住宅大厦，消防接报4" } 为什么预训练数据集是如上格式，不应该是拼接文本么？

因为这是encoder-decoder模型，属于条件生成，即是问答对的形式，decodeer-only模型一般是拼接在一起，用特定的指令符割开
