### ISSUE TITLE
tokenizer的字典中有不少token带有下划线，请问这种是什么意思

### ISSUE THREAD

**Issue by Mactarvish** [charent/ChatLM-mini-Chinese#53]
![微信图片_20240711155343](https://github.com/charent/ChatLM-mini-Chinese/assets/13399458/61be33fb-d02a-4af1-9739-64dfe21a709d)

这些带下划线的token是什么，而且有的是粗线 有的是细线

**Comment by charent** [comment]
这个是正常的，即是前缀空格的意思，`tokenzier`在设置了解码的`Metaspace`后，是看不到这个前缀的。详情请查看`tokenziers`库`add_prefix_space`和`Metaspace`参数，

**Comment by musexiaoluo** [comment]
请问 tokenizer 训练时，您的内存占多少？

**Comment by charent** [comment]
> 请问 tokenizer 训练时，您的内存占多少？

超过32G了，可能需要64G以上。
