### ISSUE TITLE
3.4预训练运行出现 unsupported operand type(s) 错误，求帮忙

### ISSUE THREAD

**Issue by summerFF** [charent/ChatLM-mini-Chinese#55]
楼主你好，我按照步骤执行到了3.4步骤时，使用jupyter-lab运行train.ipynb文件，代码执行到ChatLM-mini-Chinese/utils/functions.py文件时出现这个错误：
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 4
      1 from accelerate import notebook_launcher
      2 import torch
----> 4 from model.trainer import ChatTrainer
      5 from config import TrainConfig, T5ModelConfig

File [D:\pycharmenv\ChatLM-mini-Chinese\model\trainer.py:25](file:///D:/pycharmenv/ChatLM-mini-Chinese/model/trainer.py#line=24)
     23 from model.dataset import MyDataset
     24 from config import TrainConfig, T5ModelConfig
---> 25 from utils.functions import (
     26     get_bleu4_score, 
     27     save_model_config, 
     28     get_free_space_of_disk, 
     29     my_average,
     30     get_path_of_suffix_files,
     31     get_T5_config,
     32 )
     34 class ChatTrainer:
     35     def __init__(self, train_config: TrainConfig, model_config: T5ModelConfig, ) -> None:

File [D:\pycharmenv\ChatLM-mini-Chinese\utils\functions.py:49](file:///D:/pycharmenv/ChatLM-mini-Chinese/utils/functions.py#line=48)
     46 # 保留中文和英文、下划线，不要标点符号
     47 NON_CHAR = re.compile("[^[\u4E00-\u9FA5|A-Za-z_0-9]")
---> 49 def _get_doc_mini_hash(doc: list[str] | str, num_perm: int) -> MinHash:
     50     '''
     51     获取一段文本的mini hash
     52     '''
     53     mini_hash = MinHash(num_perm=num_perm)

TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'type'，
请问这种情况是数据类型不匹配吗

**Comment by charent** [comment]
请升级你的python到3.10及以上版本。3.9及以下版本不支持参数类型标识`doc: list[str] `，只支持`doc: List[str]`，本项目几乎所有的参数类型都是3.10之后版本的写法。

**Comment by summerFF** [comment]
> 请升级你的python到3.10及以上版本。3.9及以下版本不支持参数类型标识`doc: list[str] `，只支持`doc: List[str]`，本项目几乎所有的参数类型都是3.10之后版本的写法。

OK，感谢博主！！！
