### ISSUE TITLE
运行3.4python ptr_train.py时报错OSError: Can't load tokenizer for 'D:/pycharmenv/ChatLM-mini-Chinese/model_save/'. 

### ISSUE THREAD

**Issue by summerFF** [charent/ChatLM-mini-Chinese#56]
运行3.4python ptr_train.py时报错
(base) D:\pycharmenv\ChatLM-mini-Chinese>python pre_train.py
D:\SOFTWAREE\anacondaa\Lib\site-packages\transformers\utils\generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
D:\SOFTWAREE\anacondaa\Lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "D:\pycharmenv\ChatLM-mini-Chinese\pre_train.py", line 136, in <module>
    pre_train(config)
  File "D:\pycharmenv\ChatLM-mini-Chinese\pre_train.py", line 58, in pre_train
    tokenizer = PreTrainedTokenizerFast.from_pretrained(config.tokenizer_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SOFTWAREE\anacondaa\Lib\site-packages\transformers\tokenization_utils_base.py", line 2012, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'D:/pycharmenv/ChatLM-mini-Chinese/model_save/'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'D:/pycharmenv/ChatLM-mini-Chinese/model_save/' is the correct path to a directory containing all relevant files for a PreTrainedTokenizerFast tokenizer.

**Comment by iissy** [comment]
不是推荐3.10吗

**Comment by charent** [comment]
请参考章节[3.7 推理](https://github.com/charent/ChatLM-mini-Chinese?tab=readme-ov-file#37-%E6%8E%A8%E7%90%86)，去huggingface或者modelscope下载tokenizer相关文件放到model_save文件夹下。

**Comment by summerFF** [comment]
> 请参考章节[3.7 推理](https://github.com/charent/ChatLM-mini-Chinese?tab=readme-ov-file#37-%E6%8E%A8%E7%90%86)，去huggingface或者modelscope下载tokenizer相关文件放到model_save文件夹下。

好的，已解决，感谢博主！

**Comment by summerFF** [comment]
> 不是推荐3.10吗

感谢回复，博主推荐的python版本是3.10，问题中的3.4指得是运行步骤第3章第4步
