### ISSUE TITLE
可以介绍一下不同的任务训练的配置吗

### ISSUE THREAD

**Issue by PshySimon** [charent/ChatLM-mini-Chinese#7]
rt，想复现一下

**Comment by charent** [comment]
你说的是哪些任务的什么配置？训练参数配置还是训练样本比例的配置？如果是训练参数配置的话，文件：[config.py](https://github.com/charent/ChatLM-mini-Chinese/blob/main/config.py)有各个阶段的训练参数配置，如果是训练样本比例的配置，所有样本的处理过程见：[raw_data_process.py](https://github.com/charent/ChatLM-mini-Chinese/blob/main/utils/raw_data_process.py)和[dpo_data_process.py](https://github.com/charent/ChatLM-mini-Chinese/blob/main/utils/dpo_data_process.py)

**Comment by PshySimon** [comment]
就是gpu的配置，用的什么卡，多少张，显存是多少之类的

**Comment by charent** [comment]
请仔细阅读readme.md文件，都写有的，章节：[训练过程](https://github.com/charent/ChatLM-mini-Chinese?tab=readme-ov-file#23-%E8%AE%AD%E7%BB%83%E8%BF%87%E7%A8%8B)    

```bash
# 预训练阶段：
CPU: 28 vCPU Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz
内存：60 GB
显卡：RTX A5000(24GB) * 2

# sft及dpo阶段：
CPU: Intel(R) i5-13600k @ 5.1GHz
内存：32 GB
显卡：NVIDIA GeForce RTX 4060 Ti 16GB * 1
```

**Comment by PshySimon** [comment]
噢噢，抱歉，只看到了训练的时长，没注意上面，非常感谢耐心解答
